### ISSUE TITLE
Unify Dream Machine Support

### ISSUE THREAD

**Issue by jjanderson** [custom-components/sensor.unifigateway#17]
Hello,

On the new Unifi Dream Machine Pro, the controller is located at https://192.168.1.1/network/ not at port 8443.

Can this component be modified to handle the UDM Pro?

Thanks

**Comment by photoncloudio** [comment]
Unifi Dream Machine Pro support would be amazing. I have been using this unifi gateway sensor for ages. Really useful. When I upgraded to the UDMP recently I lost visibility, would be great to get this working! :)

**Comment by adandl** [comment]
+1 :) - would love to have UnifiOS / UDM Pro support as well

**Comment by grantclem** [comment]
Would be great to have this available

**Comment by theOrakle** [comment]
+1

**Comment by mschrag** [comment]
the newer version of pyunifi lets you specify a version="unifiOS" (rather than version="v4") which appears to be compatible with the UDM when I test it locally

**Comment by grantclem** [comment]
Noticed that also, made the change in the sensor.py  and still nothing. Changed the port to 443 also. Sensors are created, but all "unavailable".

**Comment by joggs** [comment]
I think the url to api dream machine pro is https://x.x.x.x**/proxy/network**/api/s/ instead of https://x.x.x.x/api/s/

**Comment by mathiasahlen** [comment]
+1

**Comment by curt7000** [comment]
+1

**Comment by Anon0511** [comment]
I suppose this project is dead. Just look at howold the outstanding PR is.
I tried to do the changes manually but it seems like I just don't have Python knowledge to get it working.
If anyone gets this working then please fork the project and link it.

**Comment by cdrom1028** [comment]
+1

**Comment by jchasey** [comment]
I don't have a Dream Machine but have made the changes which in theory should support one.

**Comment by rlust** [comment]
For UDMP what version should I use?

**Comment by grantclem** [comment]
> For UDMP what version should I use?

version: unifiOS

**Comment by jjanderson** [comment]
> I don't have a Dream Machine but have made the changes which in theory should support one.

Legend! Thanks so much, will test soonest!

**Comment by jchasey** [comment]
It looks like there is still an issue within the PyUnifi library that means logging into a Dream Machine does not work...please request a fix in that library and we can then inherit the fix here

**Comment by b2az** [comment]
Hi guys, i have a UDM-Pro.
This is my config:



> sensor:
>   - platform: unifigateway
    host: 10.0.1.1
    port: 443
    username: !secret unifi_user
    password: !secret unifi_password
    monitored_conditions:
      - www
      - wlan
      - alerts
      - firmware

This is the error-log:
> 2021-01-07 12:48:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for unifigateway which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-07 12:48:21 ERROR (SyncWorker_0) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
2021-01-07 12:48:21 ERROR (SyncWorker_4) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
2021-01-07 12:48:22 ERROR (SyncWorker_7) [custom_components.unifigateway.sensor] Failed to access alerts info: Expecting value: line 1 column 1 (char 0)
2021-01-07 12:48:22 ERROR (MainThread) [homeassistant.components.sensor] unifigateway: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/unifigateway/sensor.py", line 139, in update
for index, alert in enumerate(unarchived_alerts,start=1):
UnboundLocalError: local variable 'unarchived_alerts' referenced before assignment
2021-01-07 12:48:22 ERROR (SyncWorker_8) [custom_components.unifigateway.sensor] Failed to scan aps: Expecting value: line 2 column 1 (char 1)
2021-01-07 12:48:23 ERROR (MainThread) [homeassistant.components.sensor] unifigateway: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/unifigateway/sensor.py", line 155, in update
for devices in aps:
UnboundLocalError: local variable 'aps' referenced before assignment
2021-01-07 12:48:51 ERROR (SyncWorker_13) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
2021-01-07 12:48:51 ERROR (SyncWorker_3) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)

**Comment by JamieP83** [comment]
following this for UDMP updates once it works

**Comment by woodmj74** [comment]
following @b2az - seeing the same problem with USG Pro 4, get the sensors in HA but logs are the same as you, "failed to access health info"

**Comment by iJuiceman** [comment]
I have the same issue with a UDMP. Driving me nuts.

2021-02-13 17:14:02 ERROR (SyncWorker_1) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
2021-02-13 17:14:04 ERROR (SyncWorker_5) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
2021-02-13 17:14:05 ERROR (SyncWorker_2) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
2021-02-13 17:14:06 ERROR (SyncWorker_8) [custom_components.unifigateway.sensor] Failed to access alerts info: Expecting value: line 1 column 1 (char 0)

**Comment by mgottholsen** [comment]
Can confirm, also experiencing this issue with a USG4.

**Comment by guice** [comment]
Can't use the version key within the yaml anymore. It errors out: 
``` 
Invalid config for [sensor.unifigateway]: [version] is an invalid option for [sensor.unifigateway]. Check: sensor.unifigateway->version. (See ?, line ?). 
```

I tried setting `version: unifiOS` and it won't validate.

**Comment by scarpentier** [comment]
This is a [pyunifi](https://github.com/finish06/pyunifi) issue since the latest stable version does not support UDMP.

However, its `development` branch does work by using version `UDMP-unifiOS`.

I was able to put together a hack by copying the development [`controller.py`](https://github.com/finish06/pyunifi/blob/development/pyunifi/controller.py) inside `sensor.unifigateway`'s folder and updating the references.

**Comment by scarpentier** [comment]
Manually upgrading the [`pyunifi`](https://github.com/finish06/pyunifi) package to the latest development branch introduces a new `UDMP-unifiOS` version that fixes the issue (don't forget to specify port 443). 

```
python -m pip install --upgrade git+https://github.com/finish06/pyunifi.git@development
```

No code change required from `sensor.unifigateway` apart from using the lastest from master branch (so version `3.0` not `2.3`).

**Comment by ahmaddxb** [comment]
I get this but password detail are defiantly correct 

Logger: custom_components.unifigateway.sensor
Source: custom_components/unifigateway/sensor.py:91
Integration: unifigateway (documentation)
First occurred: 12:04:22 (1 occurrences)
Last logged: 12:04:22

Failed to connect to Unifi Security Gateway: Login failed - status code: 401

**Comment by guice** [comment]
@ahmaddxb  - you don't seem to have a username/password set. That would be why. At the very least, we should be seeing a `!secret username` and password in there.

Note: based on the setup, I'm going to assume you cannot use a login with 2FA. Create a service account that has no 2FA to connect to your gateway.

**Comment by ahmaddxb** [comment]
> @ahmaddxb - you don't seem to have a username/password set. That would be why. At the very least, we should be seeing a `!secret username` and password in there.
> 
> Note: based on the setup, I'm going to assume you cannot use a login with 2FA. Create a service account that has no 2FA to connect to your gateway.

I do have a username and password I just left it blank in my config I posred here, also I'm not using 2fa.

**Comment by curt7000** [comment]
I'm having a similar issue as @ahmaddxb , updated pyunifi, using unifigateway ver. 3.0, but getting a 401 login issue with a local user without 2FA.

**Comment by holblin** [comment]
Hi, I have the same issue. UDM version is 6.0.43. I have a correct login / username but I got the same error:
```
2021-03-24 08:25:42 ERROR (SyncWorker_2) [custom_components.unifigateway.sensor] Failed to connect to Unifi Security Gateway: Login failed - status code: 401
```

**Comment by holblin** [comment]
After a small research, it seems that we need the support of `UDMP-unifiOS` version which is currently in development and not release yet.
cf: https://github.com/finish06/pyunifi/tree/development

**Comment by jchasey** [comment]
Supported in latest release

**Comment by jjanderson** [comment]
Hi,

Thanks for the update, unfortunately, this update does not seem to have resolved the issue. I was using a patched version 

(https://community.home-assistant.io/t/unifi-security-gateway/71505/188) which was working, but after update (downloading and replacing the patched version with this version) I am now getting this error:

```
Logger: custom_components.unifigateway.sensor
Source: custom_components/unifigateway/sensor.py:183
Integration: unifigateway (documentation)
First occurred: 14:14:31 (16 occurrences)
Last logged: 14:17:03

Failed to access health info: Expecting value: line 2 column 1 (char 1) 
```
Here is my config:

```
- platform: unifigateway
  host: !secret unifi_host
  port: 443
  username: !secret unifi_ro_username
  password: !secret unifi_ro_password
  site_id: default
  monitored_conditions:
    - www
    - wlan
    - alerts
    - firmware
    - vpn
    - wan
```

**Comment by guice** [comment]
Updated and setting `version:` to `UDMP-unifiOS` now works on my end.

**Comment by jjanderson** [comment]
When I use `version` i get

`Invalid config for [sensor.unifigateway]: [version] is an invalid option for [sensor.unifigateway]. Check: sensor.unifigateway->version.`

```
- platform: unifigateway
  host: !secret unifi_host
  port: 443
  version: UDMP-unifiOS
  username: !secret unifi_ro_username
  password: !secret unifi_ro_password
  site_id: default
  monitored_conditions:
    - www
    - wlan
    - alerts
    - firmware
    - vpn
    - wan
```

**Comment by WhimsySpoon** [comment]
I too was using the patched version, but since installing the latest version from HACS (without the patch), the following config works for me:

```
- platform: unifigateway
  host: !secret unifi_gateway_host
  port: 443
  version: UDMP-unifiOS
  username: !secret unifi_gateway_username
  password: !secret unifi_gateway_password
```

**Comment by jjanderson** [comment]
ok, I have it working now.... it was weird as after update, I could not restart from the UI, but commenting out version, enabled the restart, and then adding in version once back up and restarting got it working... Nice one!

**Comment by xneo1** [comment]
I can also confirm that UDM with: **version: UDMP-unifiOS** also works on with Unifi OS 1.10 .
