### ISSUE TITLE
Cut release for 0.3.0

### ISSUE THREAD

**Issue by TomBrien** [custom-components/sensor.unifigateway#26]
I see that UniFi OS support was added in e010feb and the version badge was updated on readme.md after this. Is it possible to cut a 0.3.0 release so that HACS offers this version without having to install at master?

Thanks for the great work

**Comment by xPhantomNL** [comment]
I would love to see a release of this as well :)

**Comment by cdrom1028** [comment]
Bump bump.. any chance to get this soon or at lease a response to the request?

**Comment by halkeye** [comment]
I see some merges from @jchasey 2 hours ago so :crossed_fingers: 

I just found this sensor and really excited to hook up lights to new unifi alerts.

**Comment by jchasey** [comment]
New versions released
