### ISSUE TITLE
Version key in manifest file

### ISSUE THREAD

**Issue by LEJOUI** [custom-components/sensor.unifigateway#28]
Updating to the latest HA beta gives the following warning

`No 'version' key in the manifest file for custom integration 'unifigateway'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'unifigateway`

More information can be found here:

https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes

edit: changed link

**Comment by canedje** [comment]
here also:
Logger: homeassistant.loader
Source: loader.py:802
First occurred: 21:17:22 (2 occurrences)
Last logged: 21:17:24

No 'version' key in the manifest file for custom integration 'unifigateway'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'unifigateway'
No 'version' key in the manifest file for custom integration 'my_unifi'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'my_unifi'

**Comment by jchasey** [comment]
fixed in latest pull request
