### ISSUE TITLE
Templating issue

### ISSUE THREAD

**Issue by JohanEikelenboom** [custom-components/sensor.unifigateway#30]
Hi,

When I try to create the following template "{{ states.sensor.unifi_gateway_wan.attributes.tx_bytes-r }}", I get the following error: "UndefinedError: 'mappingproxy object' has no attribute 'tx_bytes'". It seems that the "-r" at the end of the sensor is being interpreted as "subtract r from states.sensor.unifi_gateway_wan.attributes.tx_byte".

Can you (try to) rename the attributes that has the minus sing (-) to use the underscore (_)?

**Comment by JohanEikelenboom** [comment]
Solved using this template:
{{ (states.sensor.unifi_gateway_wan.attributes['rx_bytes-r'] * 8 / 1024 / 1024) | round(1) }}

**Comment by chintito4ever** [comment]
Hey do you have full template of this sensor? Thank you
