### ISSUE TITLE
Getting tons of errors "Expecting value: line 2 column 1 (char 1)"

### ISSUE THREAD

**Issue by finity69x2** [custom-components/sensor.unifigateway#37]
Not sure when it started.

but getting a ton of these errors:

```
2021-03-27 19:32:00 ERROR (SyncWorker_21) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
2021-03-27 19:32:01 ERROR (SyncWorker_12) [custom_components.unifigateway.sensor] Failed to access alerts info: Expecting value: line 1 column 1 (char 0)
2021-03-27 19:32:01 ERROR (SyncWorker_28) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
2021-03-27 19:32:01 ERROR (SyncWorker_2) [custom_components.unifigateway.sensor] Failed to scan aps: Expecting value: line 2 column 1 (char 1)
2021-03-27 19:32:01 ERROR (SyncWorker_7) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
2021-03-27 19:32:01 ERROR (SyncWorker_43) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
2021-03-27 19:32:01 ERROR (SyncWorker_15) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 2 column 1 (char 1)
```

**Comment by KBrygger** [comment]
Having the same issue.

**Comment by finity69x2** [comment]
@swingerman

I added the lines as recommended from the HA thread but I'm still getting those same errors.

I assume you thought that was supposed to eliminate these errors?

If that's the case then it didn't work.

Just an FYI so that no-one thinks this issue is resolved.

**Comment by swingerman** [comment]
> @swingerman
> 
> I added the lines as recommended from the HA thread but I'm still getting those same errors.
> 
> I assume you thought that was supposed to eliminate these errors?
> 
> If that's the case then it didn't work.
> 
> Just an FYI so that no-one thinks this issue is resolved.

It also fails if if the login is unsuccessful. I know it's weird, but I tested it with PostMan. 

First, try to make sure that you can log in with the credentials using the host and port you use. This is what I tested first, and mine were wrong.

Can you confirm, your creds are OK?

**Comment by finity69x2** [comment]
I just verified and I can log in using the user I set up in HA.

the user I'm using is a "super admin" so there shouldn't be any permissions issues.

And it's the same user I set up for use with the built-in Unifi integration and that has no problems logging in.

**Comment by swingerman** [comment]
> I just verified and I can log in using the user I set up in HA.
> 
> the user I'm using is a "super admin" so there shouldn't be any permissions issues.
> 
> And it's the same user I set up for use with the built-in Unifi integration and that has no problems logging in.

Ok. If you are familiar with PostMan, you can use this [collection](https://www.getpostman.com/collections/1786db8653d2a7aa3ea2) to test locally. Just make sure you update the variables in the settings.
Please let me know how it went.

**Comment by finity69x2** [comment]
> What was the output of the `login` and `self` requests

Sorry, I've never used that before (or even heard of it :) )

I clicked on the link and it gave me a huge json looking output.

Is that the info for my unifi controller or a randomly generated one?

I have no idea what I'm supposed to be doing with that info or if I need to be entering info somewhere.

**Comment by gorillica** [comment]
I'm having the same issues. I also have a CloudKey Gen 2+, running ‘UnifiOS’ 6.1.71.

> Please let me know how it went. What was the output of the `login` and `self` requests

This is my first time using Postman, but the output from my `login` request is pretty boring:

```
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link href="/2.css" rel="stylesheet">
</head>

<body>
	<div id="root"></div>
	<script type="text/javascript" src="/vendor.0306759b.chunk.js"></script>
	<script type="text/javascript" src="/main.d8e6c715.js"></script>
</body>

</html>
```

And then from the `self` request I get exactly the same response. I'm guessing that this isn't what you see with your hardware?

**Comment by swingerman** [comment]
A login response should look like this:
`{
    "meta": {
        "rc": "ok"
    },
    "data": []
}`

From your response, it seems that you might not be using the right port.
Try to use the port where you access your controller interface

**Comment by KBrygger** [comment]
> A login response should look like this:
> `{ "meta": { "rc": "ok" }, "data": [] }`
> 
> From your response, it seems that you might not be using the right port.
> Try to use the port where you access your controller interface

I get the login response you list, but still have the issue... 

```
2021-04-22 22:35:37 ERROR (SyncWorker_14) [custom_components.unifigateway.sensor] Failed to scan aps: Expecting value: line 1 column 1 (char 0)
2021-04-22 22:36:36 ERROR (SyncWorker_14) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 1 column 1 (char 0)
2021-04-22 22:36:36 ERROR (SyncWorker_14) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 1 column 1 (char 0)
2021-04-22 22:36:36 ERROR (SyncWorker_6) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 1 column 1 (char 0)
2021-04-22 22:36:37 ERROR (SyncWorker_11) [custom_components.unifigateway.sensor] Failed to access health info: Expecting value: line 1 column 1 (char 0)
2021-04-22 22:36:37 ERROR (SyncWorker_11) [custom_components.unifigateway.sensor] Failed to access alerts info: Expecting value: line 1 column 1 (char 0)
```

**Comment by swingerman** [comment]
Ok. Now please check your config in HA to ensure it matches the config you have in postman.

**Comment by KBrygger** [comment]
> Ok. Now please check your config in HA to ensure it matches the config you have in postman.

It does... I'm using secrets and it is exactly as when I do a test login locally.

**Comment by swingerman** [comment]
Have you tried the other requests in Postman?

**Comment by KBrygger** [comment]
> Have you tried the other requests in Postman?

The Status, Sites and stat/health is looking OK it seems...

But the Self is looking like this;
{"meta":{"rc":"error","msg":"api.err.LoginRequired"},"data":[]}

**Comment by swingerman** [comment]
The login request returns a header with a token. You must set this in the corresponding variable in PostMan for the other requests. But this should work if the login works.
Have you made added the lines needed and restarted HA afterward?

**Comment by KBrygger** [comment]
> The login request returns a header with a token. You must set this in the corresponding variable in PostMan for the other requests. But this should work if the login works.
> Have you made added the lines needed and restarted HA afterward?

Short answer, yes.

It happend over night. Nothing was changed/updated when it happend. HA has been restarted multiple times after, then some changes during troubleshooting. Now everything is back as it always were when it worked :)

**Comment by SeraphimSerapis** [comment]
```
Logger: custom_components.unifigateway.sensor
Source: custom_components/unifigateway/sensor.py:157
Integration: unifigateway (documentation)
First occurred: 7:36:19 AM (53 occurrences)
Last logged: 8:28:19 AM

Failed to scan aps: Expecting value: line 1 column 1 (char 0)
```

Same issue here -- this randomly appears scattered across my logs.

**Comment by finity69x2** [comment]
OK, I think I finally figured out how to use Postman.

I'm getting the same response to the "login" and "self" as gorillica above:

```
< !doctype html >
    < html lang = "en" >
    < head >
    < meta charset = "utf-8" >
    < meta name = "viewport"
content = "width=device-width,initial-scale=1" > < link href = "/2.css"
rel = "stylesheet" > < /head> < body >
    < div id = "root" > < /div> < script type = "text/javascript"
src = "/vendor.0306759b.chunk.js" > < /script><script type="text/javascript
" src=" / main.d8e6c715.js "></script></body> < /html>
```

I have no issues at all using the same IP:PORT, user & password logging into the controller itself.

**Comment by swingerman** [comment]
This means that you are not calling the proper end point. Please check that the IP and port is valid by visiting the URL in your browser

**Comment by finity69x2** [comment]
I have. Many times. Probably almost daily. As I've said above.

my controller is at 192.168.1.4:443 and I've used the same username and password to log in with super admin rights.

If I use the same info for the Unifi integration in HA it works there, too.

Putting that same info into the integration gives the errors indicated at the start of this thread. 

And putting that into the Postman collection, saving it then running it returns those same results as above.

I'm not sure where the disconnect is.

**Comment by finity69x2** [comment]
are we sure that this integration works with V6 of the controller firmware? I'm on 6.0.45 right now.

**Comment by gorillica** [comment]
Same for me too: when I try logging in in a browser using the same combination of IP and port as I do in Postman, I log in just fine. When you log in with a CloudKey G2 now, immediately after logging in you have to choose whether you want to manage Network or Protect systems. In earlier firmware, you had separate logins for each system, so when logging into the Network, you got straight to the Network controller after logging in.

I suspect that there is a difference in the API endpoints for the CloudKey G2 as opposed to other Unifi controller devices. I've tried to work through [some of the login options here](https://ubntwiki.com/products/software/unifi-controller/api), but haven't got very far.

**Comment by finity69x2** [comment]
yeah, I think you might be onto something there. Which is related to my last question above.

this is what I get in the address bar when I go to the login page at IP:PORT (192.168.1.4:443):

"https://192.168.1.4/"

And this is where my network stars actually reside after I go to the next link ("network") from that login page:

"https://192.168.1.4/network/site/default/dashboard"

So I think, like you, that this won't work (in it's current for at least) with the Cloud Key Gen 2 running v6 firmware.

**Comment by swingerman** [comment]
@finity69x2, @gorillica 

Please note that you must use the port of the network controller, not the cloud key. They are two different things.
In my case:
Cloud Key (V6): https://192.168.1.2/ (port 443):
![ckg2](https://user-images.githubusercontent.com/7681395/117425177-3ace8680-af2b-11eb-8595-be0c16c085a7.png)

Controller: https://192.168.1.2:8443/ (port 8443) **<-- you need to log into this with the custom component** (make sure that your credentials work using the web interface)
![controller](https://user-images.githubusercontent.com/7681395/117425170-399d5980-af2b-11eb-9568-746205a6a898.png)

Hope this helps

**Comment by KBrygger** [comment]
Finally... I got mine to work :)

OK, what I did was to look at the URL and compare it to the settings. Even though I've named my site 'Unifi' it doesn't reflect the actual URL.

My URL: https://192.168.xxx.xxx:8443/manage/site/default/dashboard

My newly edited config:

```
- platform: unifigateway
  host: 192.168.xxx.xxx
  port: 8443
#  verify_ssl: false
#  site_id: unifi
  username: !secret unifi_name
  password: !secret unifi_pw
  monitored_conditions:
    - www
    - wlan
    - wan
    - lan
    - alerts
    - firmware
```

That did it for me and everything looks like it did before. So it seems that the configuration does not affect the site ID created in Unifi GUI.

**Comment by finity69x2** [comment]
I just tried to use port 8443.

in my browser as soon as I try to go to 192.168.1.4:8443 I get immediately redirected back to the cloudkey log in page (as in picture 1 in your post).

Then if I sign in there using valid credentials I can then go to the controller page (as in picture 2)

If I try to go directly to port 8443 after I sign in to the cloudkey I get "this site can't be reached" in the browser.

If I put 8443 in postman I get the following error:

```
POST https://192.168.1.4:8443/api/login
Error: connect ECONNREFUSED 192.168.1.4:8443
```

I even tried to sign out of my cloudkey account and tried again to go to port 8443 and I get the same error in postman and in the browser I get the same "this site can't be reached" error.

Do you happen to have 2FA set up in your cloudkey? Maybe that is an issue?

Or did you have to set anything up in the network controller settings to bypass requiring to log in to the cloud key first?

This all used to work like you described (I could sign directly into the controller as in your second picture without logging in to the cloud key) but a few months ago I did an update to the firmware and since that time I was required to sign in to the cloudkey first (as in picture 1) then I had the link to the controller pop up.

And I just tried it on my mobile app that I haven't used since the update and I had to set it up to use port 443 and then it asked for my 2FA information.

**Comment by gorillica** [comment]
Similar, but different, experiences for me. When I access my CloudKey on port 8443 in the browser, I just get a blank page. In Postman (and Paw, which I also use for API testing), I get error 404. In Home-Assistant, I get an error 404 notice in the logs after setting my config to use port 8443.

I wonder if there is something which turns on the ability to access individual applications on the CloudKey on separate ports? I've tried digging through all the settings in the Web UI, but can't find anything even close.

For the record, I have set up a user on the CloudKey for the HA plugin. That hasn't got any 2FA on it, although my main user has 2FA enabled.

My CloudKey firmware is 2.0.27. What's yours, @swingerman or @KBrygger?

**Comment by swingerman** [comment]
You need to set up a user in the network controller, not in the cloud key. I know it's confusing...

**Comment by finity69x2** [comment]
And how do you do that? As far as I can find there is no where in the controller to manage users. that is only done in my system in the CK.

I thought that new unifiOS removed the user config from the controller and you log in to the CK to reach the controller. Because I did originally control everything thru the controller until that firmware update. Unless I'm confused about that and I'm missing something. Which is likely.

**Comment by swingerman** [comment]
Here you go: (replace the site_id)
:8443/manage/<site_id>/settings/system/administration
- Here, you can find the  "Admins" section. 
- Add a read only admin there

**Comment by finity69x2** [comment]
that doesn't work for me.

I put in the following;

https://192.168.1.4:8443/manage/default/settings/system/administration (my site name is still "Default")

And I get "this site can't be reached"

![ex](https://user-images.githubusercontent.com/32221243/118129776-98028600-b3ca-11eb-94c9-0175568d93aa.gif)

![ex1](https://user-images.githubusercontent.com/32221243/118130295-342c8d00-b3cb-11eb-947e-821e309e0f45.gif)

**Comment by swingerman** [comment]
You seem to be using the classic UI. There should be an advanced section somewhere where you can manage the admins

**Comment by finity69x2** [comment]
I switched the settings to use the new settings UI and end up with the same result.

The new style UI settings are more limited than the classic UI settings.

> There should be an advanced section somewhere where you can manage the admins

There is but it's only in the CK:

![ex1](https://user-images.githubusercontent.com/32221243/118137197-ef0c5900-b3d2-11eb-859f-f385f6a07b4b.gif)

I'm really not trying to be dense here. I just can't figure out where the differences are between your network config and mine.

**Comment by gorillica** [comment]
Mystifying! My experience is exactly the same as @finity69x2.

**Comment by ChrisNowy** [comment]
I've fixed this error by setting version to **UDMP-unifiOS**
My CloudKey firmware version is 2.0.27.

```
sensor:
  - platform: unifigateway
    host: 192.168.1.4
    port: 443
    version: UDMP-unifiOS
    username: hass
    password: !secret unifi_hass_password
    monitored_conditions:
      - www
      - wlan
      - wan
      - lan
      - firmware

```

**Comment by finity69x2** [comment]
well, since this was so abruptly closed it would be nice for others to know that the above "version: UDMP-unifiOS" has fixed it for me.

thanks for the info.

I had tried "V6" but that obviously didn't work but I figured it almost had to be version related since nothing else seemed to work.
