### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by thetravellor** [custom-components/sensor.unifigateway#47]
Authentication fails, but am absolutely certain of username/password

I suspect  the integration has not been updated and is still trying to access the old port 8443 which is not used post 6.x

2021-10-07 09:57:00 ERROR (SyncWorker_5) [custom_components.unifigateway.sensor] Failed to connect to Unifi Security Gateway: Login failed - status code: 404

 Unifi Cloudkey Gen 2, running Network 6.4.54

**Comment by Tamsy** [comment]
Without showing what you have set inside configuration.yaml for sensor.unifigateway and what UniFi gear you have in place nobody will be able to narrow down on what is going wrong thus your issue report will most probably stay unanswered eternally.

**Comment by brodkin** [comment]
There is a "port" parameter, but it still doesn't work with v6

**Comment by thetravellor** [comment]
> 
> 
> Without showing what you have set inside configuration.yaml for sensor.unifigateway and what UniFi gear you have in place nobody will be able to narrow down on what is going wrong thus your issue report will most probably stay unanswered eternally.

Oh I do apologise, it is a Unifi Cloudkey Gen 2, running Network 6.4.54

Other unifi equipment is irrelevant.

**Comment by Tamsy** [comment]
> it is a Unifi Cloudkey Gen 2, running Network 6.4.54

Running the same device/Firmware here. On a USG4 though, not on a UDM.

Relevant config-part inside configuration.yaml:

    - platform: unifigateway
      host: 192.168.xxx.xxx  ##(<--- local (LAN) IP-address of the UniFi-CloudKey-Gen2+)
      port: 443
      version: UDMP-unifiOS
      username: !secret unifi_username
      password: !secret unifi_password
      monitored_conditions:
        - www
        - wan
        - wlan
        - lan
        - alerts
        - firmware 

Does the above skeleton help?

**Comment by thetravellor** [comment]
Resolved. Closing
